runtime: nodejs24
instance_class: F1

env_variables:
  PORT: 8080
  VITE_SUPABASE_URL: "https://lundeddnrfocejcdtamf.supabase.co"

build_env_variables:
  VITE_SUPABASE_URL: "https://lundeddnrfocejcdtamf.supabase.co"
  VITE_SUPABASE_PUBLISHABLE_KEY: "sb_publishable_PS_rzY6rg4_NtZOabYc2CA_3etnZX6O"
