name: Build, Test, and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v6.4.0
      with:
        node-version: 24.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - run: npm run test:once
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v3'
      with:
        service_account: 'avalon-engine-v2@appspot.gserviceaccount.com'
        token_format: 'access_token'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v3'
      with:
        project_id: 'avalon-engine-v2'
        env_vars: |-
          VITE_SUPABASE_SECRET_KEY="${{ secrets.VITE_SUPABASE_SECRET_KEY }}"
